# Generated by Django 2.2.7 on 2020-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(upload_to='images/')),
                ('product_type', models.IntegerField(choices=[(1, 'Food'), (2, 'Cash'), (3, 'Plantation'), (4, 'Horticulture')])),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
