# Generated by Django 3.0.3 on 2020-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('address1', models.TextField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Food'), (2, 'Cash'), (3, 'Plantation'), (4, 'Horticulture')]),
        ),
    ]
