# Generated by Django 3.0.3 on 2020-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0002_auto_20201204_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_register',
            name='address1',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
