# Generated by Django 3.0.3 on 2020-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0003_auto_20201204_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=100)),
                ('transportname1', models.CharField(max_length=100)),
                ('transportname2', models.CharField(max_length=100)),
                ('transportpassword', models.CharField(max_length=50)),
                ('transporttruck', models.PositiveSmallIntegerField()),
                ('transportcontact', models.IntegerField()),
                ('transportaddress', models.CharField(max_length=200)),
                ('transportaddress1', models.CharField(max_length=200)),
                ('transportstate', models.CharField(max_length=50)),
                ('transportdistrict', models.CharField(max_length=50)),
                ('transporttaluka', models.CharField(max_length=50)),
                ('transportcity', models.CharField(max_length=50)),
                ('transportcode', models.IntegerField()),
                ('transportaadhar', models.IntegerField()),
                ('transportgst', models.IntegerField()),
                ('aadhar', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
