# Generated by Django 3.0.3 on 2021-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0008_auto_20210110_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
