# Generated by Django 3.0.3 on 2021-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0011_auto_20210111_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport_register',
            name='transportcost',
            field=models.BigIntegerField(default=200),
            preserve_default=False,
        ),
    ]
