# Generated by Django 3.0.3 on 2021-01-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0012_transport_register_transportcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='agencyname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
