# Generated by Django 3.0.3 on 2021-01-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0019_buyer_notifications_farmer_notifications_transport_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_notifications',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sih2.Farmer_register'),
        ),
    ]
