# Generated by Django 3.0.3 on 2021-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0020_buyer_notifications_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport_notifications',
            name='agencyname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer_notifications',
            name='agencyname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
