# Generated by Django 3.0.3 on 2021-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0021_auto_20210120_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_notifications',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
