# Generated by Django 3.0.3 on 2021-01-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0022_auto_20210120_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_notifications',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transport_notifications',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
