# Generated by Django 3.0.3 on 2021-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0023_auto_20210120_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport_notifications',
            name='farmer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
