# Generated by Django 3.0.3 on 2021-01-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih2', '0024_transport_notifications_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='farmer',
        ),
    ]
